// flow-typed signature: f7e98144063954c4c9c90c95f0e0cfe5
// flow-typed version: <<STUB>>/adm-zip_v^0.4.11/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'adm-zip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'adm-zip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'adm-zip/adm-zip' {
  declare module.exports: any;
}

declare module 'adm-zip/headers/entryHeader' {
  declare module.exports: any;
}

declare module 'adm-zip/headers/index' {
  declare module.exports: any;
}

declare module 'adm-zip/headers/mainHeader' {
  declare module.exports: any;
}

declare module 'adm-zip/methods/deflater' {
  declare module.exports: any;
}

declare module 'adm-zip/methods/index' {
  declare module.exports: any;
}

declare module 'adm-zip/methods/inflater' {
  declare module.exports: any;
}

declare module 'adm-zip/util/constants' {
  declare module.exports: any;
}

declare module 'adm-zip/util/errors' {
  declare module.exports: any;
}

declare module 'adm-zip/util/fattr' {
  declare module.exports: any;
}

declare module 'adm-zip/util/fileSystem' {
  declare module.exports: any;
}

declare module 'adm-zip/util/index' {
  declare module.exports: any;
}

declare module 'adm-zip/util/utils' {
  declare module.exports: any;
}

declare module 'adm-zip/zipEntry' {
  declare module.exports: any;
}

declare module 'adm-zip/zipFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'adm-zip/adm-zip.js' {
  declare module.exports: $Exports<'adm-zip/adm-zip'>;
}
declare module 'adm-zip/headers/entryHeader.js' {
  declare module.exports: $Exports<'adm-zip/headers/entryHeader'>;
}
declare module 'adm-zip/headers/index.js' {
  declare module.exports: $Exports<'adm-zip/headers/index'>;
}
declare module 'adm-zip/headers/mainHeader.js' {
  declare module.exports: $Exports<'adm-zip/headers/mainHeader'>;
}
declare module 'adm-zip/methods/deflater.js' {
  declare module.exports: $Exports<'adm-zip/methods/deflater'>;
}
declare module 'adm-zip/methods/index.js' {
  declare module.exports: $Exports<'adm-zip/methods/index'>;
}
declare module 'adm-zip/methods/inflater.js' {
  declare module.exports: $Exports<'adm-zip/methods/inflater'>;
}
declare module 'adm-zip/util/constants.js' {
  declare module.exports: $Exports<'adm-zip/util/constants'>;
}
declare module 'adm-zip/util/errors.js' {
  declare module.exports: $Exports<'adm-zip/util/errors'>;
}
declare module 'adm-zip/util/fattr.js' {
  declare module.exports: $Exports<'adm-zip/util/fattr'>;
}
declare module 'adm-zip/util/fileSystem.js' {
  declare module.exports: $Exports<'adm-zip/util/fileSystem'>;
}
declare module 'adm-zip/util/index.js' {
  declare module.exports: $Exports<'adm-zip/util/index'>;
}
declare module 'adm-zip/util/utils.js' {
  declare module.exports: $Exports<'adm-zip/util/utils'>;
}
declare module 'adm-zip/zipEntry.js' {
  declare module.exports: $Exports<'adm-zip/zipEntry'>;
}
declare module 'adm-zip/zipFile.js' {
  declare module.exports: $Exports<'adm-zip/zipFile'>;
}
