// flow-typed signature: 462fad5951d3267d2dd28a1c214a3152
// flow-typed version: <<STUB>>/better-npm-run_v^0.1.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'better-npm-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'better-npm-run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'better-npm-run/lib/exec' {
  declare module.exports: any;
}

declare module 'better-npm-run/test/command' {
  declare module.exports: any;
}

declare module 'better-npm-run/test/env-extend' {
  declare module.exports: any;
}

declare module 'better-npm-run/test/env' {
  declare module.exports: any;
}

declare module 'better-npm-run/test/params' {
  declare module.exports: any;
}

// Filename aliases
declare module 'better-npm-run/index' {
  declare module.exports: $Exports<'better-npm-run'>;
}
declare module 'better-npm-run/index.js' {
  declare module.exports: $Exports<'better-npm-run'>;
}
declare module 'better-npm-run/lib/exec.js' {
  declare module.exports: $Exports<'better-npm-run/lib/exec'>;
}
declare module 'better-npm-run/test/command.js' {
  declare module.exports: $Exports<'better-npm-run/test/command'>;
}
declare module 'better-npm-run/test/env-extend.js' {
  declare module.exports: $Exports<'better-npm-run/test/env-extend'>;
}
declare module 'better-npm-run/test/env.js' {
  declare module.exports: $Exports<'better-npm-run/test/env'>;
}
declare module 'better-npm-run/test/params.js' {
  declare module.exports: $Exports<'better-npm-run/test/params'>;
}
