// flow-typed signature: 21b62c3208b0f85959e975d81779bc42
// flow-typed version: <<STUB>>/commitizen_v^3.0.7/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commitizen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commitizen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'commitizen/bin/commitizen' {
  declare module.exports: any;
}

declare module 'commitizen/bin/git-cz' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/commitizen' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/git-cz' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/parsers' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/parsers/commitizen' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/parsers/git-cz' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/strategies' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/strategies/git-cz' {
  declare module.exports: any;
}

declare module 'commitizen/dist/cli/strategies/git' {
  declare module.exports: any;
}

declare module 'commitizen/dist/commitizen' {
  declare module.exports: any;
}

declare module 'commitizen/dist/commitizen/adapter' {
  declare module.exports: any;
}

declare module 'commitizen/dist/commitizen/cache' {
  declare module.exports: any;
}

declare module 'commitizen/dist/commitizen/commit' {
  declare module.exports: any;
}

declare module 'commitizen/dist/commitizen/configLoader' {
  declare module.exports: any;
}

declare module 'commitizen/dist/commitizen/init' {
  declare module.exports: any;
}

declare module 'commitizen/dist/commitizen/staging' {
  declare module.exports: any;
}

declare module 'commitizen/dist/common/util' {
  declare module.exports: any;
}

declare module 'commitizen/dist/configLoader' {
  declare module.exports: any;
}

declare module 'commitizen/dist/configLoader/findup' {
  declare module.exports: any;
}

declare module 'commitizen/dist/configLoader/getContent' {
  declare module.exports: any;
}

declare module 'commitizen/dist/configLoader/getNormalizedConfig' {
  declare module.exports: any;
}

declare module 'commitizen/dist/configLoader/loader' {
  declare module.exports: any;
}

declare module 'commitizen/dist/git' {
  declare module.exports: any;
}

declare module 'commitizen/dist/git/add' {
  declare module.exports: any;
}

declare module 'commitizen/dist/git/commit' {
  declare module.exports: any;
}

declare module 'commitizen/dist/git/init' {
  declare module.exports: any;
}

declare module 'commitizen/dist/git/log' {
  declare module.exports: any;
}

declare module 'commitizen/dist/git/whatChanged' {
  declare module.exports: any;
}

declare module 'commitizen/dist/index' {
  declare module.exports: any;
}

declare module 'commitizen/dist/npm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'commitizen/bin/commitizen.js' {
  declare module.exports: $Exports<'commitizen/bin/commitizen'>;
}
declare module 'commitizen/bin/git-cz.js' {
  declare module.exports: $Exports<'commitizen/bin/git-cz'>;
}
declare module 'commitizen/dist/cli/commitizen.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/commitizen'>;
}
declare module 'commitizen/dist/cli/git-cz.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/git-cz'>;
}
declare module 'commitizen/dist/cli/parsers.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/parsers'>;
}
declare module 'commitizen/dist/cli/parsers/commitizen.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/parsers/commitizen'>;
}
declare module 'commitizen/dist/cli/parsers/git-cz.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/parsers/git-cz'>;
}
declare module 'commitizen/dist/cli/strategies.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/strategies'>;
}
declare module 'commitizen/dist/cli/strategies/git-cz.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/strategies/git-cz'>;
}
declare module 'commitizen/dist/cli/strategies/git.js' {
  declare module.exports: $Exports<'commitizen/dist/cli/strategies/git'>;
}
declare module 'commitizen/dist/commitizen.js' {
  declare module.exports: $Exports<'commitizen/dist/commitizen'>;
}
declare module 'commitizen/dist/commitizen/adapter.js' {
  declare module.exports: $Exports<'commitizen/dist/commitizen/adapter'>;
}
declare module 'commitizen/dist/commitizen/cache.js' {
  declare module.exports: $Exports<'commitizen/dist/commitizen/cache'>;
}
declare module 'commitizen/dist/commitizen/commit.js' {
  declare module.exports: $Exports<'commitizen/dist/commitizen/commit'>;
}
declare module 'commitizen/dist/commitizen/configLoader.js' {
  declare module.exports: $Exports<'commitizen/dist/commitizen/configLoader'>;
}
declare module 'commitizen/dist/commitizen/init.js' {
  declare module.exports: $Exports<'commitizen/dist/commitizen/init'>;
}
declare module 'commitizen/dist/commitizen/staging.js' {
  declare module.exports: $Exports<'commitizen/dist/commitizen/staging'>;
}
declare module 'commitizen/dist/common/util.js' {
  declare module.exports: $Exports<'commitizen/dist/common/util'>;
}
declare module 'commitizen/dist/configLoader.js' {
  declare module.exports: $Exports<'commitizen/dist/configLoader'>;
}
declare module 'commitizen/dist/configLoader/findup.js' {
  declare module.exports: $Exports<'commitizen/dist/configLoader/findup'>;
}
declare module 'commitizen/dist/configLoader/getContent.js' {
  declare module.exports: $Exports<'commitizen/dist/configLoader/getContent'>;
}
declare module 'commitizen/dist/configLoader/getNormalizedConfig.js' {
  declare module.exports: $Exports<'commitizen/dist/configLoader/getNormalizedConfig'>;
}
declare module 'commitizen/dist/configLoader/loader.js' {
  declare module.exports: $Exports<'commitizen/dist/configLoader/loader'>;
}
declare module 'commitizen/dist/git.js' {
  declare module.exports: $Exports<'commitizen/dist/git'>;
}
declare module 'commitizen/dist/git/add.js' {
  declare module.exports: $Exports<'commitizen/dist/git/add'>;
}
declare module 'commitizen/dist/git/commit.js' {
  declare module.exports: $Exports<'commitizen/dist/git/commit'>;
}
declare module 'commitizen/dist/git/init.js' {
  declare module.exports: $Exports<'commitizen/dist/git/init'>;
}
declare module 'commitizen/dist/git/log.js' {
  declare module.exports: $Exports<'commitizen/dist/git/log'>;
}
declare module 'commitizen/dist/git/whatChanged.js' {
  declare module.exports: $Exports<'commitizen/dist/git/whatChanged'>;
}
declare module 'commitizen/dist/index.js' {
  declare module.exports: $Exports<'commitizen/dist/index'>;
}
declare module 'commitizen/dist/npm.js' {
  declare module.exports: $Exports<'commitizen/dist/npm'>;
}
