// flow-typed signature: fa7d3b506d95c40d7711f4e1f63040d6
// flow-typed version: <<STUB>>/esdoc-brand-plugin_v^1.0.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-brand-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-brand-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-brand-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-brand-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-brand-plugin/src/Plugin'>;
}
