// flow-typed signature: 2cf9ab9dee0aa72972cc8665a940cee8
// flow-typed version: <<STUB>>/esdoc-standard-plugin_v^1.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-standard-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-standard-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-standard-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-standard-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-standard-plugin/src/Plugin'>;
}
