// flow-typed signature: 1eb296e5db4b035f395724ee65362a1f
// flow-typed version: <<STUB>>/esdoc-flow-type-plugin_v^1.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-flow-type-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-flow-type-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-flow-type-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-flow-type-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-flow-type-plugin/src/Plugin'>;
}
