// flow-typed signature: 2692383350f6ab6c77c8780d8eabd682
// flow-typed version: <<STUB>>/esdoc-integrate-test-plugin_v^1.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-integrate-test-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-integrate-test-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-integrate-test-plugin/src/Plugin' {
  declare module.exports: any;
}

declare module 'esdoc-integrate-test-plugin/src/TestDoc' {
  declare module.exports: any;
}

declare module 'esdoc-integrate-test-plugin/src/TestDocFactory' {
  declare module.exports: any;
}

declare module 'esdoc-integrate-test-plugin/src/TestFileDoc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-integrate-test-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-integrate-test-plugin/src/Plugin'>;
}
declare module 'esdoc-integrate-test-plugin/src/TestDoc.js' {
  declare module.exports: $Exports<'esdoc-integrate-test-plugin/src/TestDoc'>;
}
declare module 'esdoc-integrate-test-plugin/src/TestDocFactory.js' {
  declare module.exports: $Exports<'esdoc-integrate-test-plugin/src/TestDocFactory'>;
}
declare module 'esdoc-integrate-test-plugin/src/TestFileDoc.js' {
  declare module.exports: $Exports<'esdoc-integrate-test-plugin/src/TestFileDoc'>;
}
