// flow-typed signature: 736aa47bb638cfa5dab3c513afdb0fa4
// flow-typed version: <<STUB>>/esdoc-lint-plugin_v^1.0.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-lint-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-lint-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-lint-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-lint-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-lint-plugin/src/Plugin'>;
}
