// flow-typed signature: 49ed62219a3a6179c740b9519ffdefad
// flow-typed version: <<STUB>>/esdoc_v^1.1.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc/out/src/Doc/AbstractDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/AssignmentDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/ClassDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/ClassPropertyDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/ExternalDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/FileDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/FunctionDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/MemberDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/MethodDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/TypedefDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/VariableDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/ESDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/ESDocCLI' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Factory/DocFactory' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Parser/CommentParser' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Parser/ESParser' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Parser/ParamParser' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Plugin/Plugin' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Typedef/typedef' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/ASTNodeContainer' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/ASTUtil' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/InvalidCodeLogger' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/NamingUtil' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/NPMUtil' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/PathResolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc/out/src/Doc/AbstractDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/AbstractDoc'>;
}
declare module 'esdoc/out/src/Doc/AssignmentDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/AssignmentDoc'>;
}
declare module 'esdoc/out/src/Doc/ClassDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/ClassDoc'>;
}
declare module 'esdoc/out/src/Doc/ClassPropertyDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/ClassPropertyDoc'>;
}
declare module 'esdoc/out/src/Doc/ExternalDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/ExternalDoc'>;
}
declare module 'esdoc/out/src/Doc/FileDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/FileDoc'>;
}
declare module 'esdoc/out/src/Doc/FunctionDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/FunctionDoc'>;
}
declare module 'esdoc/out/src/Doc/MemberDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/MemberDoc'>;
}
declare module 'esdoc/out/src/Doc/MethodDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/MethodDoc'>;
}
declare module 'esdoc/out/src/Doc/TypedefDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/TypedefDoc'>;
}
declare module 'esdoc/out/src/Doc/VariableDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/VariableDoc'>;
}
declare module 'esdoc/out/src/ESDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/ESDoc'>;
}
declare module 'esdoc/out/src/ESDocCLI.js' {
  declare module.exports: $Exports<'esdoc/out/src/ESDocCLI'>;
}
declare module 'esdoc/out/src/Factory/DocFactory.js' {
  declare module.exports: $Exports<'esdoc/out/src/Factory/DocFactory'>;
}
declare module 'esdoc/out/src/Parser/CommentParser.js' {
  declare module.exports: $Exports<'esdoc/out/src/Parser/CommentParser'>;
}
declare module 'esdoc/out/src/Parser/ESParser.js' {
  declare module.exports: $Exports<'esdoc/out/src/Parser/ESParser'>;
}
declare module 'esdoc/out/src/Parser/ParamParser.js' {
  declare module.exports: $Exports<'esdoc/out/src/Parser/ParamParser'>;
}
declare module 'esdoc/out/src/Plugin/Plugin.js' {
  declare module.exports: $Exports<'esdoc/out/src/Plugin/Plugin'>;
}
declare module 'esdoc/out/src/Typedef/typedef.js' {
  declare module.exports: $Exports<'esdoc/out/src/Typedef/typedef'>;
}
declare module 'esdoc/out/src/Util/ASTNodeContainer.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/ASTNodeContainer'>;
}
declare module 'esdoc/out/src/Util/ASTUtil.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/ASTUtil'>;
}
declare module 'esdoc/out/src/Util/InvalidCodeLogger.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/InvalidCodeLogger'>;
}
declare module 'esdoc/out/src/Util/NamingUtil.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/NamingUtil'>;
}
declare module 'esdoc/out/src/Util/NPMUtil.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/NPMUtil'>;
}
declare module 'esdoc/out/src/Util/PathResolver.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/PathResolver'>;
}
