// flow-typed signature: 5bd39eb43de91d4748ed85801ebfa7b5
// flow-typed version: <<STUB>>/eslint-plugin-mocha-only_v^0.0.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-mocha-only'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-mocha-only' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-mocha-only/index' {
  declare module.exports: $Exports<'eslint-plugin-mocha-only'>;
}
declare module 'eslint-plugin-mocha-only/index.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha-only'>;
}
