// flow-typed signature: 14b4bd587133c2451f58358a0fc3cd2a
// flow-typed version: <<STUB>>/eslint-config-mocha_v^0.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-mocha/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-mocha/lib/merge' {
  declare module.exports: any;
}

declare module 'eslint-config-mocha/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-mocha/es6.js' {
  declare module.exports: $Exports<'eslint-config-mocha/es6'>;
}
declare module 'eslint-config-mocha/index' {
  declare module.exports: $Exports<'eslint-config-mocha'>;
}
declare module 'eslint-config-mocha/index.js' {
  declare module.exports: $Exports<'eslint-config-mocha'>;
}
declare module 'eslint-config-mocha/lib/merge.js' {
  declare module.exports: $Exports<'eslint-config-mocha/lib/merge'>;
}
declare module 'eslint-config-mocha/test.js' {
  declare module.exports: $Exports<'eslint-config-mocha/test'>;
}
