// flow-typed signature: 4947400ca3c0f87f49540c6780c0324a
// flow-typed version: <<STUB>>/eslint-config-standard_v^13.0.1/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-standard/index' {
  declare module.exports: $Exports<'eslint-config-standard'>;
}
declare module 'eslint-config-standard/index.js' {
  declare module.exports: $Exports<'eslint-config-standard'>;
}
