// flow-typed signature: b6a7b622978e0cf369abe703b443eb5a
// flow-typed version: <<STUB>>/fast-image-size_v^0.1.3/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-image-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-image-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-image-size/examples/parse_image_files' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-image-size/examples/parse_image_files.js' {
  declare module.exports: $Exports<'fast-image-size/examples/parse_image_files'>;
}
declare module 'fast-image-size/index' {
  declare module.exports: $Exports<'fast-image-size'>;
}
declare module 'fast-image-size/index.js' {
  declare module.exports: $Exports<'fast-image-size'>;
}
