// flow-typed signature: e0b0fe9bd0fcccdfee93d0c77500b621
// flow-typed version: <<STUB>>/jszip_v^2.5.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jszip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jszip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jszip/dist/jszip' {
  declare module.exports: any;
}

declare module 'jszip/dist/jszip.min' {
  declare module.exports: any;
}

declare module 'jszip/lib/arrayReader' {
  declare module.exports: any;
}

declare module 'jszip/lib/base64' {
  declare module.exports: any;
}

declare module 'jszip/lib/compressedObject' {
  declare module.exports: any;
}

declare module 'jszip/lib/compressions' {
  declare module.exports: any;
}

declare module 'jszip/lib/crc32' {
  declare module.exports: any;
}

declare module 'jszip/lib/dataReader' {
  declare module.exports: any;
}

declare module 'jszip/lib/defaults' {
  declare module.exports: any;
}

declare module 'jszip/lib/deprecatedPublicUtils' {
  declare module.exports: any;
}

declare module 'jszip/lib/flate' {
  declare module.exports: any;
}

declare module 'jszip/lib/index' {
  declare module.exports: any;
}

declare module 'jszip/lib/license_header' {
  declare module.exports: any;
}

declare module 'jszip/lib/load' {
  declare module.exports: any;
}

declare module 'jszip/lib/nodeBuffer' {
  declare module.exports: any;
}

declare module 'jszip/lib/nodeBufferReader' {
  declare module.exports: any;
}

declare module 'jszip/lib/object' {
  declare module.exports: any;
}

declare module 'jszip/lib/signature' {
  declare module.exports: any;
}

declare module 'jszip/lib/stringReader' {
  declare module.exports: any;
}

declare module 'jszip/lib/stringWriter' {
  declare module.exports: any;
}

declare module 'jszip/lib/support' {
  declare module.exports: any;
}

declare module 'jszip/lib/uint8ArrayReader' {
  declare module.exports: any;
}

declare module 'jszip/lib/uint8ArrayWriter' {
  declare module.exports: any;
}

declare module 'jszip/lib/utf8' {
  declare module.exports: any;
}

declare module 'jszip/lib/utils' {
  declare module.exports: any;
}

declare module 'jszip/lib/zipEntries' {
  declare module.exports: any;
}

declare module 'jszip/lib/zipEntry' {
  declare module.exports: any;
}

declare module 'jszip/vendor/FileSaver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jszip/dist/jszip.js' {
  declare module.exports: $Exports<'jszip/dist/jszip'>;
}
declare module 'jszip/dist/jszip.min.js' {
  declare module.exports: $Exports<'jszip/dist/jszip.min'>;
}
declare module 'jszip/lib/arrayReader.js' {
  declare module.exports: $Exports<'jszip/lib/arrayReader'>;
}
declare module 'jszip/lib/base64.js' {
  declare module.exports: $Exports<'jszip/lib/base64'>;
}
declare module 'jszip/lib/compressedObject.js' {
  declare module.exports: $Exports<'jszip/lib/compressedObject'>;
}
declare module 'jszip/lib/compressions.js' {
  declare module.exports: $Exports<'jszip/lib/compressions'>;
}
declare module 'jszip/lib/crc32.js' {
  declare module.exports: $Exports<'jszip/lib/crc32'>;
}
declare module 'jszip/lib/dataReader.js' {
  declare module.exports: $Exports<'jszip/lib/dataReader'>;
}
declare module 'jszip/lib/defaults.js' {
  declare module.exports: $Exports<'jszip/lib/defaults'>;
}
declare module 'jszip/lib/deprecatedPublicUtils.js' {
  declare module.exports: $Exports<'jszip/lib/deprecatedPublicUtils'>;
}
declare module 'jszip/lib/flate.js' {
  declare module.exports: $Exports<'jszip/lib/flate'>;
}
declare module 'jszip/lib/index.js' {
  declare module.exports: $Exports<'jszip/lib/index'>;
}
declare module 'jszip/lib/license_header.js' {
  declare module.exports: $Exports<'jszip/lib/license_header'>;
}
declare module 'jszip/lib/load.js' {
  declare module.exports: $Exports<'jszip/lib/load'>;
}
declare module 'jszip/lib/nodeBuffer.js' {
  declare module.exports: $Exports<'jszip/lib/nodeBuffer'>;
}
declare module 'jszip/lib/nodeBufferReader.js' {
  declare module.exports: $Exports<'jszip/lib/nodeBufferReader'>;
}
declare module 'jszip/lib/object.js' {
  declare module.exports: $Exports<'jszip/lib/object'>;
}
declare module 'jszip/lib/signature.js' {
  declare module.exports: $Exports<'jszip/lib/signature'>;
}
declare module 'jszip/lib/stringReader.js' {
  declare module.exports: $Exports<'jszip/lib/stringReader'>;
}
declare module 'jszip/lib/stringWriter.js' {
  declare module.exports: $Exports<'jszip/lib/stringWriter'>;
}
declare module 'jszip/lib/support.js' {
  declare module.exports: $Exports<'jszip/lib/support'>;
}
declare module 'jszip/lib/uint8ArrayReader.js' {
  declare module.exports: $Exports<'jszip/lib/uint8ArrayReader'>;
}
declare module 'jszip/lib/uint8ArrayWriter.js' {
  declare module.exports: $Exports<'jszip/lib/uint8ArrayWriter'>;
}
declare module 'jszip/lib/utf8.js' {
  declare module.exports: $Exports<'jszip/lib/utf8'>;
}
declare module 'jszip/lib/utils.js' {
  declare module.exports: $Exports<'jszip/lib/utils'>;
}
declare module 'jszip/lib/zipEntries.js' {
  declare module.exports: $Exports<'jszip/lib/zipEntries'>;
}
declare module 'jszip/lib/zipEntry.js' {
  declare module.exports: $Exports<'jszip/lib/zipEntry'>;
}
declare module 'jszip/vendor/FileSaver.js' {
  declare module.exports: $Exports<'jszip/vendor/FileSaver'>;
}
