// flow-typed signature: 96071aba64aed8ca9d38fcfbd14be83f
// flow-typed version: <<STUB>>/mocha_v^7.1.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha/browser-entry' {
  declare module.exports: any;
}

declare module 'mocha/lib/browser/growl' {
  declare module.exports: any;
}

declare module 'mocha/lib/browser/progress' {
  declare module.exports: any;
}

declare module 'mocha/lib/browser/tty' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/cli' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/collect-files' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/commands' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/config' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/init' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/node-flags' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/one-and-dones' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/options' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/run-helpers' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/run-option-metadata' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/run' {
  declare module.exports: any;
}

declare module 'mocha/lib/cli/watch-run' {
  declare module.exports: any;
}

declare module 'mocha/lib/context' {
  declare module.exports: any;
}

declare module 'mocha/lib/errors' {
  declare module.exports: any;
}

declare module 'mocha/lib/esm-utils' {
  declare module.exports: any;
}

declare module 'mocha/lib/growl' {
  declare module.exports: any;
}

declare module 'mocha/lib/hook' {
  declare module.exports: any;
}

declare module 'mocha/lib/interfaces/bdd' {
  declare module.exports: any;
}

declare module 'mocha/lib/interfaces/common' {
  declare module.exports: any;
}

declare module 'mocha/lib/interfaces/exports' {
  declare module.exports: any;
}

declare module 'mocha/lib/interfaces' {
  declare module.exports: any;
}

declare module 'mocha/lib/interfaces/qunit' {
  declare module.exports: any;
}

declare module 'mocha/lib/interfaces/tdd' {
  declare module.exports: any;
}

declare module 'mocha/lib/mocha' {
  declare module.exports: any;
}

declare module 'mocha/lib/pending' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/base' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/doc' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/dot' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/html' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/json-stream' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/json' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/landing' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/list' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/markdown' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/min' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/nyan' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/progress' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/spec' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/tap' {
  declare module.exports: any;
}

declare module 'mocha/lib/reporters/xunit' {
  declare module.exports: any;
}

declare module 'mocha/lib/runnable' {
  declare module.exports: any;
}

declare module 'mocha/lib/runner' {
  declare module.exports: any;
}

declare module 'mocha/lib/stats-collector' {
  declare module.exports: any;
}

declare module 'mocha/lib/suite' {
  declare module.exports: any;
}

declare module 'mocha/lib/test' {
  declare module.exports: any;
}

declare module 'mocha/lib/utils' {
  declare module.exports: any;
}

declare module 'mocha/mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha/browser-entry.js' {
  declare module.exports: $Exports<'mocha/browser-entry'>;
}
declare module 'mocha/index' {
  declare module.exports: $Exports<'mocha'>;
}
declare module 'mocha/index.js' {
  declare module.exports: $Exports<'mocha'>;
}
declare module 'mocha/lib/browser/growl.js' {
  declare module.exports: $Exports<'mocha/lib/browser/growl'>;
}
declare module 'mocha/lib/browser/progress.js' {
  declare module.exports: $Exports<'mocha/lib/browser/progress'>;
}
declare module 'mocha/lib/browser/tty.js' {
  declare module.exports: $Exports<'mocha/lib/browser/tty'>;
}
declare module 'mocha/lib/cli/cli.js' {
  declare module.exports: $Exports<'mocha/lib/cli/cli'>;
}
declare module 'mocha/lib/cli/collect-files.js' {
  declare module.exports: $Exports<'mocha/lib/cli/collect-files'>;
}
declare module 'mocha/lib/cli/commands.js' {
  declare module.exports: $Exports<'mocha/lib/cli/commands'>;
}
declare module 'mocha/lib/cli/config.js' {
  declare module.exports: $Exports<'mocha/lib/cli/config'>;
}
declare module 'mocha/lib/cli/index' {
  declare module.exports: $Exports<'mocha/lib/cli'>;
}
declare module 'mocha/lib/cli/index.js' {
  declare module.exports: $Exports<'mocha/lib/cli'>;
}
declare module 'mocha/lib/cli/init.js' {
  declare module.exports: $Exports<'mocha/lib/cli/init'>;
}
declare module 'mocha/lib/cli/node-flags.js' {
  declare module.exports: $Exports<'mocha/lib/cli/node-flags'>;
}
declare module 'mocha/lib/cli/one-and-dones.js' {
  declare module.exports: $Exports<'mocha/lib/cli/one-and-dones'>;
}
declare module 'mocha/lib/cli/options.js' {
  declare module.exports: $Exports<'mocha/lib/cli/options'>;
}
declare module 'mocha/lib/cli/run-helpers.js' {
  declare module.exports: $Exports<'mocha/lib/cli/run-helpers'>;
}
declare module 'mocha/lib/cli/run-option-metadata.js' {
  declare module.exports: $Exports<'mocha/lib/cli/run-option-metadata'>;
}
declare module 'mocha/lib/cli/run.js' {
  declare module.exports: $Exports<'mocha/lib/cli/run'>;
}
declare module 'mocha/lib/cli/watch-run.js' {
  declare module.exports: $Exports<'mocha/lib/cli/watch-run'>;
}
declare module 'mocha/lib/context.js' {
  declare module.exports: $Exports<'mocha/lib/context'>;
}
declare module 'mocha/lib/errors.js' {
  declare module.exports: $Exports<'mocha/lib/errors'>;
}
declare module 'mocha/lib/esm-utils.js' {
  declare module.exports: $Exports<'mocha/lib/esm-utils'>;
}
declare module 'mocha/lib/growl.js' {
  declare module.exports: $Exports<'mocha/lib/growl'>;
}
declare module 'mocha/lib/hook.js' {
  declare module.exports: $Exports<'mocha/lib/hook'>;
}
declare module 'mocha/lib/interfaces/bdd.js' {
  declare module.exports: $Exports<'mocha/lib/interfaces/bdd'>;
}
declare module 'mocha/lib/interfaces/common.js' {
  declare module.exports: $Exports<'mocha/lib/interfaces/common'>;
}
declare module 'mocha/lib/interfaces/exports.js' {
  declare module.exports: $Exports<'mocha/lib/interfaces/exports'>;
}
declare module 'mocha/lib/interfaces/index' {
  declare module.exports: $Exports<'mocha/lib/interfaces'>;
}
declare module 'mocha/lib/interfaces/index.js' {
  declare module.exports: $Exports<'mocha/lib/interfaces'>;
}
declare module 'mocha/lib/interfaces/qunit.js' {
  declare module.exports: $Exports<'mocha/lib/interfaces/qunit'>;
}
declare module 'mocha/lib/interfaces/tdd.js' {
  declare module.exports: $Exports<'mocha/lib/interfaces/tdd'>;
}
declare module 'mocha/lib/mocha.js' {
  declare module.exports: $Exports<'mocha/lib/mocha'>;
}
declare module 'mocha/lib/pending.js' {
  declare module.exports: $Exports<'mocha/lib/pending'>;
}
declare module 'mocha/lib/reporters/base.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/base'>;
}
declare module 'mocha/lib/reporters/doc.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/doc'>;
}
declare module 'mocha/lib/reporters/dot.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/dot'>;
}
declare module 'mocha/lib/reporters/html.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/html'>;
}
declare module 'mocha/lib/reporters/index' {
  declare module.exports: $Exports<'mocha/lib/reporters'>;
}
declare module 'mocha/lib/reporters/index.js' {
  declare module.exports: $Exports<'mocha/lib/reporters'>;
}
declare module 'mocha/lib/reporters/json-stream.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/json-stream'>;
}
declare module 'mocha/lib/reporters/json.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/json'>;
}
declare module 'mocha/lib/reporters/landing.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/landing'>;
}
declare module 'mocha/lib/reporters/list.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/list'>;
}
declare module 'mocha/lib/reporters/markdown.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/markdown'>;
}
declare module 'mocha/lib/reporters/min.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/min'>;
}
declare module 'mocha/lib/reporters/nyan.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/nyan'>;
}
declare module 'mocha/lib/reporters/progress.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/progress'>;
}
declare module 'mocha/lib/reporters/spec.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/spec'>;
}
declare module 'mocha/lib/reporters/tap.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/tap'>;
}
declare module 'mocha/lib/reporters/xunit.js' {
  declare module.exports: $Exports<'mocha/lib/reporters/xunit'>;
}
declare module 'mocha/lib/runnable.js' {
  declare module.exports: $Exports<'mocha/lib/runnable'>;
}
declare module 'mocha/lib/runner.js' {
  declare module.exports: $Exports<'mocha/lib/runner'>;
}
declare module 'mocha/lib/stats-collector.js' {
  declare module.exports: $Exports<'mocha/lib/stats-collector'>;
}
declare module 'mocha/lib/suite.js' {
  declare module.exports: $Exports<'mocha/lib/suite'>;
}
declare module 'mocha/lib/test.js' {
  declare module.exports: $Exports<'mocha/lib/test'>;
}
declare module 'mocha/lib/utils.js' {
  declare module.exports: $Exports<'mocha/lib/utils'>;
}
declare module 'mocha/mocha.js' {
  declare module.exports: $Exports<'mocha/mocha'>;
}
