// flow-typed signature: cbbf5c87ce9c2fca3302f9ab5ee4835a
// flow-typed version: <<STUB>>/readable-stream_v~3.3.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'readable-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'readable-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'readable-stream/errors-browser' {
  declare module.exports: any;
}

declare module 'readable-stream/errors' {
  declare module.exports: any;
}

declare module 'readable-stream/experimentalWarning' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/_stream_duplex' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/_stream_passthrough' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/_stream_readable' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/_stream_transform' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/_stream_writable' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/async_iterator' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/buffer_list' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/destroy' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/end-of-stream' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/pipeline' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/state' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/stream-browser' {
  declare module.exports: any;
}

declare module 'readable-stream/lib/internal/streams/stream' {
  declare module.exports: any;
}

declare module 'readable-stream/readable-browser' {
  declare module.exports: any;
}

declare module 'readable-stream/readable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'readable-stream/errors-browser.js' {
  declare module.exports: $Exports<'readable-stream/errors-browser'>;
}
declare module 'readable-stream/errors.js' {
  declare module.exports: $Exports<'readable-stream/errors'>;
}
declare module 'readable-stream/experimentalWarning.js' {
  declare module.exports: $Exports<'readable-stream/experimentalWarning'>;
}
declare module 'readable-stream/lib/_stream_duplex.js' {
  declare module.exports: $Exports<'readable-stream/lib/_stream_duplex'>;
}
declare module 'readable-stream/lib/_stream_passthrough.js' {
  declare module.exports: $Exports<'readable-stream/lib/_stream_passthrough'>;
}
declare module 'readable-stream/lib/_stream_readable.js' {
  declare module.exports: $Exports<'readable-stream/lib/_stream_readable'>;
}
declare module 'readable-stream/lib/_stream_transform.js' {
  declare module.exports: $Exports<'readable-stream/lib/_stream_transform'>;
}
declare module 'readable-stream/lib/_stream_writable.js' {
  declare module.exports: $Exports<'readable-stream/lib/_stream_writable'>;
}
declare module 'readable-stream/lib/internal/streams/async_iterator.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/async_iterator'>;
}
declare module 'readable-stream/lib/internal/streams/buffer_list.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/buffer_list'>;
}
declare module 'readable-stream/lib/internal/streams/destroy.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/destroy'>;
}
declare module 'readable-stream/lib/internal/streams/end-of-stream.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/end-of-stream'>;
}
declare module 'readable-stream/lib/internal/streams/pipeline.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/pipeline'>;
}
declare module 'readable-stream/lib/internal/streams/state.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/state'>;
}
declare module 'readable-stream/lib/internal/streams/stream-browser.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/stream-browser'>;
}
declare module 'readable-stream/lib/internal/streams/stream.js' {
  declare module.exports: $Exports<'readable-stream/lib/internal/streams/stream'>;
}
declare module 'readable-stream/readable-browser.js' {
  declare module.exports: $Exports<'readable-stream/readable-browser'>;
}
declare module 'readable-stream/readable.js' {
  declare module.exports: $Exports<'readable-stream/readable'>;
}
