// flow-typed signature: 0c1b54f0a47ba106a15f6167dcdc19c9
// flow-typed version: <<STUB>>/rollup-plugin-cpy_v^1.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-cpy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-cpy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-cpy/dist/rollup-plugin-cpy.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cpy/dist/rollup-plugin-cpy.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-cpy/dist/rollup-plugin-cpy.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-cpy/dist/rollup-plugin-cpy.cjs'>;
}
declare module 'rollup-plugin-cpy/dist/rollup-plugin-cpy.es.js' {
  declare module.exports: $Exports<'rollup-plugin-cpy/dist/rollup-plugin-cpy.es'>;
}
