// flow-typed signature: 7c52aa0a2a705b7be251642b25bee2cc
// flow-typed version: <<STUB>>/rollup_v^1.19.4/flow_v0.105.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup/dist/rollup.browser.es' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup.browser' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup.es' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/chunk' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup/dist/rollup.browser.es.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.browser.es'>;
}
declare module 'rollup/dist/rollup.browser.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.browser'>;
}
declare module 'rollup/dist/rollup.es.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.es'>;
}
declare module 'rollup/dist/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/rollup'>;
}
declare module 'rollup/dist/shared/chunk.js' {
  declare module.exports: $Exports<'rollup/dist/shared/chunk'>;
}
declare module 'rollup/dist/shared/index' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
declare module 'rollup/dist/shared/index.js' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
