// flow-typed signature: bd5779933b0544aa3c03a2384738b1ff
// flow-typed version: <<STUB>>/setimmediate_v~1.0.5/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'setimmediate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'setimmediate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'setimmediate/setImmediate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'setimmediate/setImmediate.js' {
  declare module.exports: $Exports<'setimmediate/setImmediate'>;
}
