// flow-typed signature: 28a272b57b98f069abb9c74d106b9adc
// flow-typed version: <<STUB>>/xmlbuilder_v^12.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xmlbuilder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xmlbuilder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xmlbuilder/lib/Derivation' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/DocumentPosition' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/index' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/NodeType' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/OperationType' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/Utility' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/WriterState' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLAttribute' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLCData' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLCharacterData' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLComment' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDeclaration' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDocType' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDocument' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDocumentCB' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDocumentFragment' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDOMConfiguration' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDOMErrorHandler' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDOMImplementation' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDOMStringList' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDAttList' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDElement' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDEntity' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDNotation' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDummy' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLElement' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLNamedNodeMap' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLNode' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLNodeFilter' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLNodeList' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLProcessingInstruction' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLRaw' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLStreamWriter' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLStringifier' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLStringWriter' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLText' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLTypeInfo' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLUserDataHandler' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLWriterBase' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xmlbuilder/lib/Derivation.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/Derivation'>;
}
declare module 'xmlbuilder/lib/DocumentPosition.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/DocumentPosition'>;
}
declare module 'xmlbuilder/lib/index.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/index'>;
}
declare module 'xmlbuilder/lib/NodeType.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/NodeType'>;
}
declare module 'xmlbuilder/lib/OperationType.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/OperationType'>;
}
declare module 'xmlbuilder/lib/Utility.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/Utility'>;
}
declare module 'xmlbuilder/lib/WriterState.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/WriterState'>;
}
declare module 'xmlbuilder/lib/XMLAttribute.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLAttribute'>;
}
declare module 'xmlbuilder/lib/XMLCData.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLCData'>;
}
declare module 'xmlbuilder/lib/XMLCharacterData.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLCharacterData'>;
}
declare module 'xmlbuilder/lib/XMLComment.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLComment'>;
}
declare module 'xmlbuilder/lib/XMLDeclaration.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDeclaration'>;
}
declare module 'xmlbuilder/lib/XMLDocType.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDocType'>;
}
declare module 'xmlbuilder/lib/XMLDocument.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDocument'>;
}
declare module 'xmlbuilder/lib/XMLDocumentCB.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDocumentCB'>;
}
declare module 'xmlbuilder/lib/XMLDocumentFragment.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDocumentFragment'>;
}
declare module 'xmlbuilder/lib/XMLDOMConfiguration.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDOMConfiguration'>;
}
declare module 'xmlbuilder/lib/XMLDOMErrorHandler.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDOMErrorHandler'>;
}
declare module 'xmlbuilder/lib/XMLDOMImplementation.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDOMImplementation'>;
}
declare module 'xmlbuilder/lib/XMLDOMStringList.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDOMStringList'>;
}
declare module 'xmlbuilder/lib/XMLDTDAttList.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDAttList'>;
}
declare module 'xmlbuilder/lib/XMLDTDElement.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDElement'>;
}
declare module 'xmlbuilder/lib/XMLDTDEntity.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDEntity'>;
}
declare module 'xmlbuilder/lib/XMLDTDNotation.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDNotation'>;
}
declare module 'xmlbuilder/lib/XMLDummy.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDummy'>;
}
declare module 'xmlbuilder/lib/XMLElement.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLElement'>;
}
declare module 'xmlbuilder/lib/XMLNamedNodeMap.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLNamedNodeMap'>;
}
declare module 'xmlbuilder/lib/XMLNode.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLNode'>;
}
declare module 'xmlbuilder/lib/XMLNodeFilter.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLNodeFilter'>;
}
declare module 'xmlbuilder/lib/XMLNodeList.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLNodeList'>;
}
declare module 'xmlbuilder/lib/XMLProcessingInstruction.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLProcessingInstruction'>;
}
declare module 'xmlbuilder/lib/XMLRaw.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLRaw'>;
}
declare module 'xmlbuilder/lib/XMLStreamWriter.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLStreamWriter'>;
}
declare module 'xmlbuilder/lib/XMLStringifier.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLStringifier'>;
}
declare module 'xmlbuilder/lib/XMLStringWriter.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLStringWriter'>;
}
declare module 'xmlbuilder/lib/XMLText.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLText'>;
}
declare module 'xmlbuilder/lib/XMLTypeInfo.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLTypeInfo'>;
}
declare module 'xmlbuilder/lib/XMLUserDataHandler.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLUserDataHandler'>;
}
declare module 'xmlbuilder/lib/XMLWriterBase.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLWriterBase'>;
}
