// flow-typed signature: 8ba4afab1bfa6c92dec6f69ea2388717
// flow-typed version: <<STUB>>/xmlbuilder_v^3.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xmlbuilder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xmlbuilder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xmlbuilder/lib/index' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLAttribute' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLBuilder' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLCData' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLComment' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDeclaration' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDocType' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDAttList' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDElement' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDEntity' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLDTDNotation' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLElement' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLNode' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLProcessingInstruction' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLRaw' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLStringifier' {
  declare module.exports: any;
}

declare module 'xmlbuilder/lib/XMLText' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xmlbuilder/lib/index.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/index'>;
}
declare module 'xmlbuilder/lib/XMLAttribute.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLAttribute'>;
}
declare module 'xmlbuilder/lib/XMLBuilder.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLBuilder'>;
}
declare module 'xmlbuilder/lib/XMLCData.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLCData'>;
}
declare module 'xmlbuilder/lib/XMLComment.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLComment'>;
}
declare module 'xmlbuilder/lib/XMLDeclaration.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDeclaration'>;
}
declare module 'xmlbuilder/lib/XMLDocType.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDocType'>;
}
declare module 'xmlbuilder/lib/XMLDTDAttList.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDAttList'>;
}
declare module 'xmlbuilder/lib/XMLDTDElement.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDElement'>;
}
declare module 'xmlbuilder/lib/XMLDTDEntity.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDEntity'>;
}
declare module 'xmlbuilder/lib/XMLDTDNotation.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLDTDNotation'>;
}
declare module 'xmlbuilder/lib/XMLElement.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLElement'>;
}
declare module 'xmlbuilder/lib/XMLNode.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLNode'>;
}
declare module 'xmlbuilder/lib/XMLProcessingInstruction.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLProcessingInstruction'>;
}
declare module 'xmlbuilder/lib/XMLRaw.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLRaw'>;
}
declare module 'xmlbuilder/lib/XMLStringifier.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLStringifier'>;
}
declare module 'xmlbuilder/lib/XMLText.js' {
  declare module.exports: $Exports<'xmlbuilder/lib/XMLText'>;
}
